# Generated by Django 3.2.12 on 2022-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(default='Light Grey', max_length=20)),
                ('colour_hex', models.CharField(default='#D6DBDF', max_length=20)),
            ],
        ),
    ]
