# Generated by Django 3.2.12 on 2022-03-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0003_admonish_adm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admonish',
            name='adm_term',
            field=models.CharField(default='', max_length=200),
        ),
    ]
