# Generated by Django 3.2.12 on 2022-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0004_admonish_adm_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twe_dict', models.CharField(default='', max_length=5000)),
                ('twe_seshn', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
