# Generated by Django 3.2.12 on 2022-03-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0005_tweetlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetlists',
            name='twe_term',
            field=models.CharField(default='', max_length=20),
        ),
    ]
