# Generated by Django 3.2.12 on 2022-03-14 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0011_alter_tweetlists_twe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlists',
            name='twe_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 21, 36, 20, 135680)),
        ),
    ]
