# Generated by Django 3.2.12 on 2022-03-18 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0013_alter_tweetlists_twe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlists',
            name='twe_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 20, 26, 49, 6021, tzinfo=utc)),
        ),
    ]
