# Generated by Django 3.2.12 on 2022-03-18 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

#     dependencies = [
#         ('spelling', '0016_alter_tweetlists_twe_time'),
#     ]

    operations = [
        migrations.AlterField(
            model_name='tweetlists',
            name='twe_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
