# Generated by Django 3.2.12 on 2022-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0017_alter_tweetlists_twe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetlists',
            name='twe_dict',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
