# Generated by Django 3.2.12 on 2022-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20220410_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
