# Generated by Django 3.2.12 on 2022-04-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_alter_entry_date_written'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_written',
            new_name='date_modified',
        ),
    ]
