# Generated by Django 3.2.12 on 2022-04-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_rename_date_written_entry_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_modified',
            new_name='last_modified',
        ),
    ]
