# Generated by Django 3.2.12 on 2022-04-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.CharField(choices=[('Jon', 'J'), ('Stef', 'S'), ('Nick', 'Me'), ('Nicky', 'N')], max_length=5),
        ),
    ]
