# Generated by Django 3.2.12 on 2022-04-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_alter_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mod_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user',
            field=models.CharField(choices=[('Jon', 'J'), ('Stef', 'S'), ('Nick', 'Me'), ('Nicky', 'N')], default='', max_length=20),
        ),
    ]
