# Generated by Django 3.2.12 on 2022-04-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20220424_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtime',
            name='send_time',
            field=models.CharField(default='00:00', max_length=100),
        ),
    ]
