# Generated by Django 3.2.12 on 2022-04-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plp', '0002_auto_20220401_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='savequery',
            name='goodness',
            field=models.CharField(default='', max_length=5),
        ),
    ]
