# Generated by Django 3.2.12 on 2022-04-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plp', '0003_savequery_goodness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savequery',
            old_name='q_res',
            new_name='badness',
        ),
        migrations.AlterField(
            model_name='savequery',
            name='goodness',
            field=models.CharField(max_length=5000),
        ),
    ]
