# Generated by Django 3.2.12 on 2022-04-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plp', '0005_savequery_the_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveQuery',
        ),
    ]
