# Generated by Django 3.2.12 on 2022-02-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squaresg', '0003_auto_20220213_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clab', models.IntegerField(default=0)),
                ('sessiony', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
    ]
