# Generated by Django 3.2.12 on 2022-02-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squaresg', '0005_auto_20220217_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstInd',
        ),
    ]
