# Generated by Django 3.2.12 on 2022-03-24 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squaresg', '0006_delete_firstind'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exceppo',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.DeleteModel(
            name='Times',
        ),
    ]
